support cgroup driver is cgroupfs
AliyunContainerService/terway-qos pull request #13
Opened 2023-11-28 12:03 UTC by lucming

1. some code optimisation
2.  support cgroup driver is cgroupfs
```bash
[root@docker82 liuming6]# ls /sys/fs/cgroup/net_cls
cgroup.clone_children  cgroup.sane_behavior  kubepods         net_prio.ifpriomap  notify_on_release  release_agent
cgroup.procs           docker                net_cls.classid  net_prio.prioidx    pool_size          tasks
[root@docker82 liuming6]#
```
Here we can see that the pod-related cgroups are all in the /sys/fs/cgroup/${type}/kubepods/ directory, but only the cgroup information under kubepods.slice was processed previously

2023-11-29 03:11 UTC, lucming commented
PTAL @l1b0k

2023-11-29 14:05 UTC, l1b0k requested changes

2023-11-29 14:05 UTC, l1b0k commented on pkg/bpf/maps.go
> +		if err := w.obj.PodMap.Delete(ip2Addr(ip)); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
should check ip IsValid

2023-11-29 14:05 UTC, l1b0k commented on pkg/k8s/pods.go
>  func getIPs(pod *corev1.Pod) (v4 netip.Addr, v6 netip.Addr) {
i got a another. FYI.

```go

func getIPs(pod *corev1.Pod) (v4 netip.Addr, v6 netip.Addr) {
	ips := []string{pod.Status.PodIP}
	for _, ip := range pod.Status.PodIPs {
		ips = append(ips, ip.IP)
	}

	for _, ip := range ips {
		addr, err := netip.ParseAddr(ip)
		if err != nil {
			continue
		}
		if addr.Is4() {
			v4 = addr
		}
		v6 = addr
	}
	return
}
```

2023-11-30 06:34 UTC, lucming commented on pkg/bpf/maps.go
> +		if err := w.obj.PodMap.Delete(ip2Addr(ip)); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
done

2023-11-30 06:34 UTC, lucming commented on pkg/k8s/pods.go
>  func getIPs(pod *corev1.Pod) (v4 netip.Addr, v6 netip.Addr) {
done

2023-11-30 11:50 UTC, l1b0k approved these changes

2023-11-30 11:50 UTC, merged

2023-11-30 11:51 UTC, l1b0k commented
Thanks.